### ISSUE TITLE
Bobby b hello

### ISSUE THREAD

**Issue by tomaroyal** [Aniket-Pradhan/snek#8]
Hello Bobby b

**Comment by King-Bobby-B** [comment]
They never tell you how they all shit themselves. They don't put that part in the songs... stupid boy. Now the Tarlys bend the knee like everyone else. He could have lingered on the edge of the battle with the smart boys, and today his wife would be making him miserable, his sons would be ingrates, and he'd be waking three times in the night to piss into a bowl.
